#for AWS CodeBuild

#this version MUST be 0.2 as per AWS CodeBuild BuildSpec file rules
version: 0.2

env:
  variables:
     toolset_branch: "master"
     server_type: "local"
     used_modules: "check_cache,code_coverage"
     ros_release_name: "kinetic"
     ubuntu_version_name: "xenial"
     docker_image_name: "shadowrobot/build-tools:xenial-kinetic"
     relative_job_path: "/home/user"
     unit_tests_result_dir: "$relative_job_path/unit_tests"
     coverage_tests_result_dir: "$relative_job_path/code_coverage"
     remote_shell_script: "https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh"
phases:
  build:
    commands:
      - echo Build started on `date`
      - env
      - ls -la "$relative_job_path"
      - cp -r $CODEBUILD_SRC_DIR/* /home/user/workspace/src/
      - echo Running $remote_shell_script with stdin values $toolset_branch $server_type $used_modules $relative_job_path
      - curl -s "$( echo "$remote_shell_script" | sed 's/#/%23/g' )" | bash /dev/stdin $toolset_branch $server_type $used_modules $relative_job_path 
artifacts:
  files:
    - 'codecoverage/*'
    - 'testresults/*'
  base-directory: '/home/user'
