version: 2
jobs:
  build:
    docker:
      - image: shadowrobot/build-tools:xenial-kinetic
        environment:
          toolset_branch: F#SRC-1420_circle_ci_2_0 # DEBUG: Change to master
          server_type: circle2 # DEBUG: change to circle
          ros_release_name: kinetic
          ubuntu_version_name: xenial
#          used_modules: check_cache,check_build,code_style_check,check_deb_make,codecov_tool
          used_modules: check_cache,code_style_check

    steps:
      - checkout
      - run: whoami
      - run: ls -al ~/
      - run: ls -al $HOME
      - run: ls -al $CIRCLE_WORKING_DIRECTORY
      - run: echo 'export remote_shell_script="https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh"' >> $BASH_ENV
      - run: wget -O /tmp/oneliner "$( echo "$remote_shell_script" | sed 's/#/%23/g' )"
      - run: gosu root chown -R $MY_USERNAME:$MY_USERNAME $CIRCLE_WORKING_DIRECTORY
      - run: chmod 755 /tmp/oneliner
      - run: cd /tmp
      - run: gosu $MY_USERNAME /tmp/oneliner "$toolset_branch" $server_type $used_modules
